name: CI Tests


on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - name: mamba installs
      run: |
        pip install flake8 pytest
    - name: install gsl
      run: |
        sudo apt-get install -y libgsl-dev
        - name: install X-PSI package
    - name: Test with pytest
      run: |
        pytest
