name: Docs
on:
  push:
    branches:
      - main
  release:
  workflow_dispatch:
permissions: write-all  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      max-parallel: 5
      
    steps:
    - name: Set up GCC
      run: |
         sudo apt-get install -y gcc
    - name: install gsl
      run: |
        sudo apt-get install -y libgsl-dev
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        pip install sphinx
        pip install ipynb
        pip install ipykernel
        pip install pandas
        pip install numpy
        pip install scipy
        pip install jupyter
        pip install matplotlib
        pip install ultranest
        pip install NumbaMinpack
        pip install CompactObject-TOV==1.8.1
    - name : install docs dependencies
      run: |
        pip install decorator h5py 
        pip install nbsphinx nbconvert
        pip install sphinxcontrib-websupport sphinx_rtd_theme
        conda install pandoc
    - name: Install pandoc
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.15/pandoc-2.15-linux-amd64.tar.gz
        tar xvzf pandoc-2.15-linux-amd64.tar.gz
        sudo mv pandoc-2.15/bin/pandoc /usr/local/bin
        rm -rf pandoc-2.15 pandoc-2.15-linux-amd64.tar.gz
    - name: Sphinx build
      run: |
        sphinx-build docs/source _build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/
        force_orphan: true
