name: Docs

on:
  push:
    branches:
      - main
  release:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        pip install sphinx sphinx_rtd_theme
        pip install nbsphinx
        conda install pandoc
        pip install ipynb
        pip install ipykernel
        pip install pandas
        pip install numpy
        pip install matplotlib
        pip install scipy
        pip install CompactObject-TOV
    - name : install docs dependencies
      run: |
        micromamba install sphinx=1.8.5 decorator=4.4.1 h5py 
        micromamba install -c conda-forge nbsphinx=0.5.1 nbconvert=5.6.1
        pip install sphinxcontrib-websupport==1.1.2 sphinx_rtd_theme==0.4.3
    - name : build docs
      run: make html
      working-directory: docs/
    - name : move docs
      run : |
        mkdir ../../../../py2
        mv build/html/* ../../../../py2/
      working-directory: docs/
    - name: check CompactObject
      uses: actions/checkout@v3
      with:
        ref: main
    - name : install docs dependencies
      run: |
        micromamba install sphinx decorator h5py
        micromamba install -c conda-forge nbsphinx nbconvert
        pip install sphinxcontrib-websupport sphinx_rtd_theme
    - name : build docs
      run: | 
        make html
        mkdir build/html/py2
        mv ../../../../py2/* build/html/py2/  
      working-directory: docs/

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: docs/build/html
        jekyll: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
